# Generated by Django 4.2.4 on 2023-10-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greeting_card", "0002_greetingcard_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="greetingcard",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
