# Generated by Django 4.2 on 2023-05-04 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(editable=False, verbose_name='date added')),
                ('is_available', models.BooleanField(default=True)),
                ('available_date', models.DateTimeField(verbose_name='date modified access')),
                ('edit_date', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
        migrations.CreateModel(
            name='SectionKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('data', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('login', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(editable=False, verbose_name='date added')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('content', models.CharField(max_length=10000)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sectionkind')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sectionstatus')),
                ('status_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.statusdata')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(editable=False, verbose_name='date added')),
                ('is_available', models.BooleanField(default=True)),
                ('available_date', models.DateTimeField(verbose_name='date modified access')),
                ('edit_date', models.DateTimeField(verbose_name='date modified')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.catalog')),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
    ]
