# Generated by Django 4.2 on 2023-05-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_catalog_sectionkind_sectionstatus_statusdata_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='parent_dir',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.catalog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='parent_dir',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='polls.catalog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
    ]
