# Generated by Django 4.2 on 2023-05-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_catalog_parent_dir_file_parent_dir_alter_file_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='parent_dir',
        ),
        migrations.RemoveField(
            model_name='file',
            name='parent_dir',
        ),
    ]
