# Generated by Django 4.2 on 2023-05-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_catalog_parent_dir_remove_file_parent_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='parent_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.catalog'),
        ),
        migrations.AddField(
            model_name='file',
            name='parent_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.catalog'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='add_date',
            field=models.DateTimeField(verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='add_date',
            field=models.DateTimeField(verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
