# Generated by Django 4.2 on 2023-05-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_catalog_parent_dir_file_parent_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.file'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
