# Generated by Django 4.2 on 2023-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_section_file_alter_section_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='add_date',
            field=models.DateTimeField(verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
