# Generated by Django 4.2 on 2023-05-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_section_add_date_alter_section_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.JSONField(blank=True, max_length=1000),
        ),
    ]
