# Generated by Django 4.2 on 2023-05-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_section_kind_alter_section_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='add_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date added'),
        ),
    ]
