# Generated by Django 4.2 on 2023-05-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_section_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='file',
            name='available_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date modified access'),
        ),
        migrations.AlterField(
            model_name='file',
            name='edit_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
        migrations.AlterField(
            model_name='section',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
    ]
