# Generated by Django 4.2 on 2023-05-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_file_add_date_alter_file_available_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='available_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date modified access'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='edit_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date modified'),
        ),
    ]
