# Generated by Django 4.2 on 2023-05-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_file_owner_alter_file_parent_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
