# Generated by Django 4.2.4 on 2023-10-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("greeting_card", "0003_greetingcard_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="greetingcard",
            name="template",
            field=models.TextField(default="normal"),
            preserve_default=False,
        ),
    ]
